#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Vamshi Krishna Santhapuri
"""Local KVM/QEMU subprocess provider — speaks JSON-RPC over stdin/stdout.

Builds hardened images on the machine running Stratum, no cloud account
required. Boots a base cloud image under ``qemu-system-x86_64`` (hardware
accelerated via KVM when available, falling back to slower TCG software
emulation), injects SSH access via a cloud-init NoCloud seed, then reuses
the same Ansible-Lockdown hardening + OpenSCAP scanning flow every other
Stratum provider uses. The output artifact is a qcow2 (optionally converted
to raw) file rather than a cloud-native image reference.

Run as a standalone script: the core Stratum engine never imports this file.
Logs go to stderr; only JSON-RPC responses go to stdout.

Requires (system packages, not pip): qemu-system-x86, qemu-img, and either
cloud-image-utils (cloud-localds) or genisoimage.

Credential fields (stored via Stratum integrations UI — all optional, this
provider needs no account/API key):
    memory_mb   — Guest RAM in MB (default: 2048)
    cpus        — Guest vCPU count (default: 2)

Blueprint usage:
    target:
      provider: kvm
      base_image: "ubuntu22.04"   # downloadable OS slug, or a path to a qcow2 you already have
"""

from __future__ import annotations

import json
import logging
import os
import sys
import tempfile
import uuid
from pathlib import Path

PROVIDER_NAME = "kvm"

logging.basicConfig(stream=sys.stderr, level=logging.INFO, format="[kvm] %(message)s")
logger = logging.getLogger(__name__)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _provider_utils as utils  # noqa: E402
import _qemu_utils as qemu  # noqa: E402

_LOCAL_IMAGES_DIR = Path("data/local-images")
_BUILDS_DIR = Path("data/builds")

_SSH_WAIT_TIMEOUT = 300
_SHUTDOWN_TIMEOUT = 60


# ---------------------------------------------------------------------------
# JSON-RPC helpers
# ---------------------------------------------------------------------------


def _ok(id, result):
    return {"jsonrpc": "2.0", "id": id, "result": result}


def _err(id, code, message):
    return {"jsonrpc": "2.0", "id": id, "error": {"code": code, "message": message}}


# ---------------------------------------------------------------------------
# RPC handlers
# ---------------------------------------------------------------------------


def test_connection(params: dict) -> dict:
    """Verify the host has everything needed to boot a local QEMU VM."""
    import shutil as _shutil

    missing = [b for b in ("qemu-system-x86_64", "qemu-img") if _shutil.which(b) is None]
    if missing:
        raise RuntimeError(f"Missing required binaries on PATH: {missing}")
    if _shutil.which("cloud-localds") is None and _shutil.which("genisoimage") is None:
        raise RuntimeError("Neither 'cloud-localds' nor 'genisoimage' is on PATH — cannot build a cloud-init seed ISO")

    kvm_ok = qemu.kvm_available()
    return {
        "status": "ok",
        "kvm_acceleration": kvm_ok,
        "note": "Builds will use slower TCG software emulation"
        if not kvm_ok
        else "KVM hardware acceleration available",
    }


def execute_build(params: dict) -> dict:
    """Boot a base image locally, harden it, scan it, and snapshot to qcow2/raw.

    Param fields:
        base_image      — downloadable OS slug (e.g. "ubuntu22.04") or a path to an existing qcow2
        os              — OS identifier for lockdown role / ssh user selection
        instance_type   — ignored (use credentials.memory_mb / credentials.cpus instead)
        root_volume_size_gb — overlay virtual disk size; cloud-init's growpart/resizefs
                              expand the guest's root partition to fill it (default: 20)
        profile_name / profile_version — for artifact metadata
        hardening / prehard_playbook_yaml — as generated by the core pipeline
        profile / datastream — SCAP profile and datastream path
        output_format   — "qcow2" (default) or "raw"
        credentials.memory_mb / credentials.cpus — guest resources
    """
    credentials = params.get("credentials", {}) or {}
    os_name = params.get("os", "ubuntu22.04")
    base_image_ref = params.get("base_image", "") or os_name
    profile_name = params.get("profile_name", "unnamed")
    profile_version = params.get("profile_version", "0.0.0")
    profile_id = params.get("profile", "")
    datastream = params.get("datastream", "")
    prehard_playbook_yaml: str = params.get("prehard_playbook_yaml", "")
    hardening_config = params.get("hardening", {})
    output_format = (params.get("output_format") or "qcow2").lower()
    if output_format not in ("qcow2", "raw"):
        raise ValueError(f"output_format must be 'qcow2' or 'raw', got {output_format!r}")

    memory_mb = int(credentials.get("memory_mb") or 2048)
    cpus = int(credentials.get("cpus") or 2)
    disk_gb = int(params.get("root_volume_size_gb") or 20)
    ssh_user = utils.default_ssh_user(os_name)

    job_id = str(uuid.uuid4())
    build_dir = _BUILDS_DIR / job_id
    build_dir.mkdir(parents=True, exist_ok=True)

    base_path = qemu.resolve_base_image(base_image_ref, os_name, _LOCAL_IMAGES_DIR)
    overlay_path = build_dir / "overlay.qcow2"
    qemu.create_overlay(base_path, overlay_path, size_gb=disk_gb)

    proc = None
    with tempfile.TemporaryDirectory(prefix="stratum-kvm-") as tmpdir:
        tmp = Path(tmpdir)
        key_path, pub_key = utils.generate_ssh_keypair(tmp)
        seed_iso = qemu.build_seed_iso(tmp, pub_key, ssh_user, hostname=f"stratum-{job_id[:8]}")
        ssh_port = qemu.find_free_port()
        serial_log = build_dir / "serial.log"

        try:
            proc = qemu.launch_qemu(overlay_path, seed_iso, ssh_port, serial_log, memory_mb=memory_mb, cpus=cpus)

            host_ip = "127.0.0.1"
            logger.info("Waiting for guest SSH on %s:%d…", host_ip, ssh_port)
            utils.wait_for_ssh(host_ip, port=ssh_port, timeout=_SSH_WAIT_TIMEOUT)
            # wait_for_ssh only checks the TCP listener — sshd itself commonly
            # resets the first few connections while it finishes starting up
            # (regenerating host keys, etc.), with an inconsistent error each
            # time. Retry unconditionally until a real command succeeds.
            qemu.wait_for_ssh_ready(host_ip, ssh_user, key_path, port=ssh_port, timeout=120)
            utils.wait_for_cloud_init(host_ip, ssh_user, key_path, timeout=180, port=ssh_port)

            if prehard_playbook_yaml:
                logger.info("Applying pre-hardening configuration…")
                utils.install_ansible_on_remote(host_ip, ssh_user, key_path, port=ssh_port)
                utils.run_prehard_ansible_remote(host_ip, ssh_user, key_path, prehard_playbook_yaml, port=ssh_port)

            logger.info("Running compliance hardening…")
            utils.install_ansible_on_remote(host_ip, ssh_user, key_path, port=ssh_port)
            utils.run_hardening_remote(host_ip, ssh_user, key_path, os_name, hardening_config, port=ssh_port)

            logger.info("Running OpenSCAP scan…")
            utils.install_oscap_on_remote(host_ip, ssh_user, key_path, port=ssh_port)
            utils.run_oscap_remote(host_ip, ssh_user, key_path, profile_id, datastream, port=ssh_port)

            utils.cleanup_instance_history_remote(host_ip, ssh_user, key_path, port=ssh_port)

            logger.info("Shutting down guest cleanly…")
            utils.run_remote_cmd(
                host_ip, ssh_user, key_path, "sudo shutdown -h now", check=False, timeout=30, port=ssh_port
            )
            if not qemu.wait_for_process_exit(proc, timeout=_SHUTDOWN_TIMEOUT):
                logger.warning("Guest did not shut down within %ds — terminating QEMU", _SHUTDOWN_TIMEOUT)
                qemu.terminate_qemu(proc)
            proc = None  # already exited/terminated

        finally:
            if proc is not None:
                qemu.terminate_qemu(proc)

    final_image_path = overlay_path
    if output_format == "raw":
        raw_path = build_dir / "image.raw"
        qemu.convert_to_raw(overlay_path, raw_path)
        overlay_path.unlink(missing_ok=True)
        final_image_path = raw_path
    else:
        final_image_path = build_dir / "image.qcow2"
        overlay_path.rename(final_image_path)

    checksum = qemu.sha256_file(final_image_path)
    (build_dir / f"{final_image_path.name}.sha256").write_text(f"{checksum}  {final_image_path.name}\n")
    metadata = {
        "profile_name": profile_name,
        "profile_version": profile_version,
        "os": os_name,
        "compliance_profile": profile_id,
        "output_format": output_format,
        "sha256": checksum,
        "size_bytes": final_image_path.stat().st_size,
        "base_image": str(base_path),
    }
    (build_dir / "metadata.json").write_text(json.dumps(metadata, indent=2))

    return {
        "status": "success",
        "artifact_id": str(final_image_path),
        "artifact_type": output_format,
        "region": "local",
        "metadata": metadata,
    }


def list_images(params: dict) -> dict:
    """Return locally built artifacts under data/builds/."""
    images = []
    if _BUILDS_DIR.is_dir():
        for build_dir in sorted(_BUILDS_DIR.iterdir()):
            meta_path = build_dir / "metadata.json"
            if not meta_path.is_file():
                continue
            try:
                meta = json.loads(meta_path.read_text())
            except Exception:
                continue
            images.append(
                {
                    "id": build_dir.name,
                    "name": meta.get("profile_name", build_dir.name),
                    "output_format": meta.get("output_format", "qcow2"),
                    "size_bytes": meta.get("size_bytes", 0),
                    "os": meta.get("os", ""),
                }
            )
    return {"images": images}


_DISPATCH = {
    "test_connection": test_connection,
    "execute_build": execute_build,
    "list_images": list_images,
}


def main() -> None:
    raw = sys.stdin.read()
    try:
        req = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps(_err(None, -32700, f"Parse error: {exc}")), flush=True)
        sys.exit(1)

    req_id = req.get("id")
    method = req.get("method")
    params = req.get("params", {})

    if method not in _DISPATCH:
        print(json.dumps(_err(req_id, -32601, f"Method not found: {method!r}")), flush=True)
        sys.exit(1)

    try:
        result = _DISPATCH[method](params)
        print(json.dumps(_ok(req_id, result)), flush=True)
    except Exception as exc:
        logger.error("execute error: %s", exc)
        print(json.dumps(_err(req_id, -32603, str(exc))), flush=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
